### ISSUE TITLE
Cursor is off-set

### ISSUE THREAD

**Issue by lordscarlet** [sixteencolors/js-textmode-editor#24]
The cursor is displaying 40px or so to the right of the actual cursor position

**Comment by bricas** [comment]
Magically fixed. _shrug_

**Comment by bricas** [comment]
This one is a bit different now, where -- as you go down the screen (y-axis), the cursor position is ever-so-slightly above where it should be.

**Comment by lordscarlet** [comment]
Huh, sorry you had to describe that, I thought I already did. I think I hit "re-open" and that lost my comment.
